name: nike
on:
  schedule:
    - cron:  '0 0 * * 0,2'
env:
  GH_TOKEN: ${{secrets.GH_TOKEN}}
jobs:
  kadin_job:
    uses: ./.github/workflows/reusable.yml
    with:
      GENDER: kadin
      maxconcurrency: '1'
      WEBSITE: 'biraradamoda'
      marka: 'nike'
    secrets: inherit
  erkek_job:
    uses: ./.github/workflows/reusable.yml
    with:
      GENDER: erkek
      maxconcurrency: '1'
      WEBSITE: 'biraradamoda'
      marka: 'nike'
    secrets: inherit
  kcocuk_job:
    uses: ./.github/workflows/reusable.yml
    with:
      GENDER: kcocuk
      maxconcurrency: '1'
      WEBSITE: 'biraradamoda'
      marka: 'nike'
    secrets: inherit
  ecocuk_job:
    uses: ./.github/workflows/reusable.yml
    with:
      GENDER: ecocuk
      maxconcurrency: '1'
      WEBSITE: 'biraradamoda'
      marka: 'nike'
    secrets: inherit
