

function getSearchUrls({ searchterm }) {

    const brands = {
        abiyefon: { url: `https://www.abiyefon.com/search/?q=${searchterm.replaceAll(' ', '+')}`,group:['elbise'],searchterm  },
        addax: { url: `https://www.addax.com.tr/tr/p/Cat/NewSearch?sr=${searchterm.replaceAll(' ', '+')}`,group:['elbise'],searchterm  },
        adidas: { url: `https://www.adidas.com.tr/tr/${searchterm.replaceAll(' ', '_')}` ,group:['spor']},
        adl: { url: `https://www.adl.com.tr/list/?search_text=${searchterm.replaceAll(' ', '+')}`,group:['elbise'],searchterm  },
        alinderi: { url: `https://alinderi.com.tr/module/iqitsearch/searchiqit?s=${searchterm.replaceAll(' ', '+')}`,group:['deri'],searchterm  },
        alpinist: { url: `https://www.alpinist.com.tr/arama/${searchterm.replaceAll(' ', '%20')}`,group:['outdoor'],searchterm  },
        armine:{ group:["kadın",'tesettür','çanta','giyim'], url:`https://www.armine.com/Arama?1&kelime=${searchterm.replaceAll(' ', '%20')} }`, searchterm },
        avva:{group:['erkek'],           url:`https://www.avva.com.tr/Arama?1&kelime=${searchterm.replaceAll(' ', '%20')}`, searchterm},
        bagmori:{group:['çanta','kadın'],url:`https://www.bagmori.com/search?q=beyaz+%C3%A7anta${searchterm.replaceAll(' ', '+')}`,searchterm },
        bambiayakkabi:{group:['kadın','erkek','ayakkabı','çanta'] ,url:`https://www.bambiayakkabi.com.tr/Arama?1&kelime=${searchterm.replaceAll(' ', '%20')}`,searchterm},
        baqa:{ group:['kadın'], url:`https://www.baqa.com.tr/Arama?1&kelime=${searchterm.replaceAll(' ', '%20')}?currency=try`,searchterm},
      //  bershka:{},
        beymen:{group:['kadın','erkek','çocuk'],url:`https://www.beymen.com/search?q=${searchterm.replaceAll(' ', '%20')}`,searchterm},
      //  beymenclub:{},
        beyyoglu:{group:['kadin','erkek','çanta'],url:`https://www.beyyoglu.com/list/?search_text=${searchterm.replaceAll(' ', '%20') }`,searchterm },
        blacknoble:{group:['kadın','erkek','çocuk'],url:`https://www.blacknoble.com/Arama?1&kelime=${searchterm.replaceAll(' ', '%20')}`,searchterm} ,
        bsl:{group:['kadın'],url:`https://www.bsl.com.tr/tr/p/NewCat/NewSearch?sr=${searchterm.replaceAll(' ', '+')}`,searchterm},
        butigo:{group:['']},
        buyukmoda:{},
        bysaygi:{},
        centone:{},
        colins:{},
        defacto:{},
        dericeket:{},
        dericlub:{},
        deriderim:{},
        derimod:{},
        deristore:{},
        desa:{},
        dilvin:{},
        divarese:{},
        dogostore:{},
        elleshoes:{},
        exquise:{},
        fashionfriends:{},
        gizia:{},
        hm:{},
        hotic:{},
        ikbalderi:{},
        ipekyol:{},
        jimmykey:{},
        kigili:{},
        koton:{},
        lacht:{},
        lcwaikiki:{},
        levis:{},
        lovemybody:{},
        machka:{},
        mango:{},
        manuka:{},
        markapia:{},
        matras:{},
        mavijeans:{},
        miostil:{},
        network:{},
        nike:{},
        nu:{},
        olegassini:{},
        oxxo:{},
        panco:{},
        patirti:{},
        penti:{},
        perspective:{},
        pierricardin:{},
        puma:{},
        quzu:{},
        roman:{},
        sarar:{},
        sementa:{},
        slatra:{},
        stradivarus:{},
        tamertanca:{},
        tergan:{},
        tiffanytomato:{},
        tommylife:{},
        tonnyblack:{},
        tozlu:{},
        twist:{},
        uspoloassn:{},
        vakko:{},
        valiberta:{},
        vitrin:{},
        wcollection:{},
        wrangler:{},
        xint:{},
        yargici:{},
        zara:{}
    }

    return Object.entries(brands)

}


module.exports = {
    getSearchUrls
}