name: lcwaikiki
on:
  schedule:
    - cron:  '0 0 * * 5,1'

env:
  GH_TOKEN: ${{secrets.GH_TOKEN}}
jobs:
  kadin_job:
    uses: ./.github/workflows/reusable.yml
    with:
      GENDER: kadin
      maxconcurrency: '2'
      WEBSITE: 'biraradamoda'
      marka: 'lcwaikiki'
    secrets: inherit
  # erkek_job:
  #   uses: ./.github/workflows/reusable.yml
  #   with:
  #     GENDER: erkek
  #     maxconcurrency: '2'
  #     WEBSITE: 'biraradamoda'
  #     marka: 'lcwaikiki'
  #   secrets: inherit
  # kcocuk_job:
  #   uses: ./.github/workflows/reusable.yml
  #   with:
  #     GENDER: kcocuk
  #     maxconcurrency: '2'
  #     WEBSITE: 'biraradamoda'
  #     marka: 'lcwaikiki'
  #   secrets: inherit
  # ecocuk_job:
  #   uses: ./.github/workflows/reusable.yml
  #   with:
  #     GENDER: ecocuk
  #     maxconcurrency: '2'
  #     WEBSITE: 'biraradamoda'
  #     marka: 'lcwaikiki'
  #   secrets: inherit
