name: tergan
on:
  schedule:
    - cron:  '0 0 * * 6,1'
env:
  GH_TOKEN: ${{secrets.GH_TOKEN}}
jobs:
  kadin_job:
    uses: ./.github/workflows/reusable.yml
    with:
      GENDER: kadin
      maxconcurrency: '1'
      WEBSITE: 'biraradamoda'
      marka: 'tergan'
    secrets: inherit
  erkek_job:
    uses: ./.github/workflows/reusable.yml
    with:
      GENDER: erkek
      maxconcurrency: '1'
      WEBSITE: 'biraradamoda'
      marka: 'tergan'
    secrets: inherit